pipelines:
  default:
    - step:
        name: Sync GitHub Mirror
        image: alpine/git:latest
        clone:
          enabled: false
        script:
          - git clone --bare git@bitbucket.org:romaswe/java-chat-app.git
          - cd java-chat-app
          - git push --mirror git@github.com:romaswe/java-chat-app.git